Add solutions to exercises
Cambridge-ICCS/ml-training-material pull request #14
Opened 2023-07-15 10:07 UTC by jdenholm

Adding full worked solutions to each exercise:

- [ ] Penguin classification.
- [ ] Penguin regression.
- [ ] MNIST classification.
- [ ] CNN regression.

2023-07-26 16:03 UTC, jatkinson1000 approved these changes
I've been through all of these as individual PRs, and again here (see a few more typo fixes).

I'm now happy that they match to the exercises, are correct and functional, and make sense.

However, it would be good to have an independent pair of eyes look over them so I'll leave this open for now in case anyone else has a chance to look.

2023-07-31 15:14 UTC, mondus requested changes
I ran out of time today to go through this in details but checked the first two examples worked in the notebook by running them through. Can confirm they work as expected. I would however suggest/request to remove all cell outputs before committing so that users have a "clean" workbook prior to running cells.

2023-07-31 17:12 UTC, TomMelt reviewed
I have a couple of suggestions and I have also submitted a PR #23  with some typos fixes. I recommend merging that and then you can optionally address the comments below.

2023-07-31 17:12 UTC, TomMelt commented on exercise-solutions/01_penguin_classification_solutions.ipynb
> +    "    drop_last=True,\n",
In `train_loader` you use `drop_last=True` but not in the `valid_loader`. Why is that? maybe add it to the explanation above? e.g., "the normalization step only runs when training the model so it is not necessary for validation".

2023-07-31 17:12 UTC, TomMelt commented on exercise-solutions/01_penguin_classification_solutions.ipynb
> +    "    The ``torch.nn.Sequential`` allows us to \"chain\" multiple layers, rather\n",
The `torch.nn.Sequential` [method/class/function etc?] allows us ....
or
`torch.nn.Sequential` allows us ...

2023-07-31 17:12 UTC, TomMelt commented on exercise-solutions/02_penguin_regression_solutions.ipynb
> +    "``Adam`` is regarded as the king of optimisers: let's use it again, but this time with a learning rate.\n",
Maybe briefly describe what learning rate is in simple-ish terms?

2023-07-31 17:12 UTC, TomMelt commented on exercise-solutions/02_penguin_regression_solutions.ipynb
> +    "While this losses have decreased nicely, MSE isn't the most easily interpretable way to evaluate the model's performance. We could instead look at the ratio of the predictions  targets—and in pa
This part of the sentence doesn't make sense to me... "We could instead look at the ratio of the predictions targets".

Am I missing something?

2023-07-31 17:14 UTC, jatkinson1000 commented
@mondus We cleared the books for the lab, but since these are worked solutions I feel there is some merit to having example output present should people just be reading and not running, or running their version in parallel.
Any thoughts @jdenholm ?

2023-07-31 17:15 UTC, jatkinson1000 commented on exercise-solutions/02_penguin_regression_solutions.ipynb
> +    "While this losses have decreased nicely, MSE isn't the most easily interpretable way to evaluate the model's performance. We could instead look at the ratio of the predictions  targets—and in pa
Should be a 'to' in there, I'll fix.

2023-07-31 17:16 UTC, jatkinson1000 commented on exercise-solutions/02_penguin_regression_solutions.ipynb
> +    "``Adam`` is regarded as the king of optimisers: let's use it again, but this time with a learning rate.\n",
This was done in the slides, but worth mentioning again/referring to lectures. I'll add.

2023-07-31 17:16 UTC, jatkinson1000 commented on exercise-solutions/01_penguin_classification_solutions.ipynb
> +    "    The ``torch.nn.Sequential`` allows us to \"chain\" multiple layers, rather\n",
Will amend.

2023-08-01 09:12 UTC, jatkinson1000 commented on exercise-solutions/02_penguin_regression_solutions.ipynb
> +    "``Adam`` is regarded as the king of optimisers: let's use it again, but this time with a learning rate.\n",
Link to Adam Docs is in there.

2023-08-01 09:17 UTC, jatkinson1000 commented on exercise-solutions/01_penguin_classification_solutions.ipynb
> +    "    drop_last=True,\n",
Added comment.

2023-08-01 09:35 UTC, TomMelt approved these changes

2023-08-02 18:26 UTC, jdenholm commented
> @mondus We cleared the books for the lab, but since these are worked solutions I feel there is some merit to having example output present should people just be reading and not running, or running their version in parallel. Any thoughts @jdenholm ?

I can see your point as much as I can see Paul's. If the user doesn't have a particularly beefy laptop, they might find running the CNN examples challenging, so I think I lean slightly towards leaving them in.

2023-08-02 19:54 UTC, jatkinson1000 commented
Cool, thanks.
In that case if you're happy to approve this for merging @mondus I'll get it done and sent to participants.

2023-08-04 09:34 UTC, jatkinson1000 commented
This will close #13

2023-08-04 09:38 UTC, mondus approved these changes

2023-08-04 09:54 UTC, merged